server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
  # jpa properties
  jpa:
    hibernate:
      ddl-auto: none # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate:
        # ?? insert
        jdbc:
          batch_size: 1000

        format_sql: false
        highlight_sql: true
        # generate_statistics: true
        order_updates: true
        order_inserts: true

    # ??? ??? ??? ?? ???
    defer-datasource-initialization: false

  sql:
    init:
      platform: postgres
  data:
    web:
      pageable:
        one-indexed-parameters: true
